### ISSUE TITLE
Wrong location for iPhone + (landscape)

### ISSUE THREAD

**Issue by twobitfool** [cubiq/add-to-homescreen#118]
In landscape mode, the iPhone 6 Plus moves the buttons to the top.

![iphone-6-plus-landscape](https://cloud.githubusercontent.com/assets/12453/4528441/ca51c428-4d6e-11e4-92fe-3eb895d6b1ab.png)

**Comment by maddy2get** [comment]
I am having different but same issue. It shows popup at wrong position. Please see the attached image. 

Device: iPhone 5s
OS: iOS 8.1.1

It works fine for iPhone 6 with same iOS 8.1.1

![iphone-5s-ios-8 1 1](https://cloud.githubusercontent.com/assets/1869939/5733524/3228b944-9bf8-11e4-8b5d-485cd615cc8f.jpg)

Any idea on how to fix this?

Thanks,
Sanjay

**Comment by cubiq** [comment]
I thought this was fixed... are you using the latest version?

**Comment by maddy2get** [comment]
It doesn't seem so unfortunately. Any help would be appreciated. Thanks.

**Comment by cubiq** [comment]
it's just a matter of changing the CSS a bit, I'll have a look at it

**Comment by maddy2get** [comment]
I agree. May be media query based on screen size and .ath-ios8.

**Comment by rbrewer** [comment]
I'm still seeing the incorrect popup location reported earlier in this thread by @maddy2get (and in closed issue #116) on iOS 8.1.3 on a real iPhone 5 with the latest version of add-to-homescreen. Should I create a new issue @cubiq, or do you want to reopen #116? BTW, thanks for making this great little library available.
